import type { BlockDefinition } from "@/lib/block-types";
import TestimonialsLayout from "./layout";
import { TestimonialsEditable } from "./editable";
import { TestimonialsPanelControls } from "./panel";

const testimonials: BlockDefinition = {
  name: "testimonials",
  label: "Testimonials",
  icon: "testimonials",
  category: "design",
  defaultData: {
    design: "classic",
    navigation: false,
    speed: 5000,
    random: false,
    speechBubble: true,
    columns: 2,
    gap: "1.5rem",
    padding: "1.75rem",
    borderRadius: "0.5rem",
    borderStyle: "solid",
    borderColor: "#e4e4e7",
    borderTop: "1px",
    borderRight: "1px",
    borderBottom: "1px",
    borderLeft: "1px",
    bgColor: "",
    textColor: "",
    nameColor: "",
    navColor: "",
    navSize: "",
    items: [
      {
        id: "t1",
        quote: "Working with this team was an absolute pleasure. The results exceeded all expectations and the communication was excellent throughout.",
        name: "Sarah Johnson",
        company: "Brightline Co.",
        companyLink: "",
        companyTarget: "_self",
        photo: "",
        photoRadius: "",
        avatar: "placeholder",
        avatarPosition: "above",
        avatarSize: "",
        icon: "",
        iconAlignment: "left",
        rating: 5,
      },
      {
        id: "t2",
        quote: "Incredible attention to detail and a genuine passion for quality. I wouldn't hesitate to recommend them to anyone.",
        name: "Mark Williams",
        company: "Keystone Labs",
        companyLink: "",
        companyTarget: "_self",
        photo: "",
        photoRadius: "",
        avatar: "placeholder",
        avatarPosition: "above",
        avatarSize: "",
        icon: "",
        iconAlignment: "left",
        rating: 5,
      },
    ],
  },
  Layout: TestimonialsLayout,
  Editable: TestimonialsEditable,
  PanelControls: TestimonialsPanelControls,
};

export default testimonials;
