/**
 * Per-block UI translations registry
 * ───────────────────────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To translate a block's chrome: add per-locale files under blocks/<name>/lang/
 * (e.g. lang/en.json, lang/de.json), each shaped as { "<key>": "<string>" }.
 * The next dev / build process regenerates this file automatically.
 *
 * Resolve strings via the helpers in @/lib/i18n/block-messages.
 */

import audio_de from "../../blocks/audio/lang/de.json";
import audio_en from "../../blocks/audio/lang/en.json";
import audio_it from "../../blocks/audio/lang/it.json";
import button_de from "../../blocks/button/lang/de.json";
import button_en from "../../blocks/button/lang/en.json";
import button_it from "../../blocks/button/lang/it.json";
import carousel_de from "../../blocks/carousel/lang/de.json";
import carousel_en from "../../blocks/carousel/lang/en.json";
import carousel_it from "../../blocks/carousel/lang/it.json";
import chart_de from "../../blocks/chart/lang/de.json";
import chart_en from "../../blocks/chart/lang/en.json";
import chart_it from "../../blocks/chart/lang/it.json";
import code_de from "../../blocks/code/lang/de.json";
import code_en from "../../blocks/code/lang/en.json";
import code_it from "../../blocks/code/lang/it.json";
import columns_de from "../../blocks/columns/lang/de.json";
import columns_en from "../../blocks/columns/lang/en.json";
import columns_it from "../../blocks/columns/lang/it.json";
import countdown_de from "../../blocks/countdown/lang/de.json";
import countdown_en from "../../blocks/countdown/lang/en.json";
import countdown_it from "../../blocks/countdown/lang/it.json";
import counter_de from "../../blocks/counter/lang/de.json";
import counter_en from "../../blocks/counter/lang/en.json";
import counter_it from "../../blocks/counter/lang/it.json";
import delimiter_de from "../../blocks/delimiter/lang/de.json";
import delimiter_en from "../../blocks/delimiter/lang/en.json";
import delimiter_it from "../../blocks/delimiter/lang/it.json";
import embed_de from "../../blocks/embed/lang/de.json";
import embed_en from "../../blocks/embed/lang/en.json";
import embed_it from "../../blocks/embed/lang/it.json";
import flickr_de from "../../blocks/flickr/lang/de.json";
import flickr_en from "../../blocks/flickr/lang/en.json";
import flickr_it from "../../blocks/flickr/lang/it.json";
import gallery_de from "../../blocks/gallery/lang/de.json";
import gallery_en from "../../blocks/gallery/lang/en.json";
import gallery_it from "../../blocks/gallery/lang/it.json";
import header_de from "../../blocks/header/lang/de.json";
import header_en from "../../blocks/header/lang/en.json";
import header_it from "../../blocks/header/lang/it.json";
import html_de from "../../blocks/html/lang/de.json";
import html_en from "../../blocks/html/lang/en.json";
import html_it from "../../blocks/html/lang/it.json";
import image_de from "../../blocks/image/lang/de.json";
import image_en from "../../blocks/image/lang/en.json";
import image_it from "../../blocks/image/lang/it.json";
import instagram_de from "../../blocks/instagram/lang/de.json";
import instagram_en from "../../blocks/instagram/lang/en.json";
import instagram_it from "../../blocks/instagram/lang/it.json";
import list_de from "../../blocks/list/lang/de.json";
import list_en from "../../blocks/list/lang/en.json";
import list_it from "../../blocks/list/lang/it.json";
import newsTicker_de from "../../blocks/news-ticker/lang/de.json";
import newsTicker_en from "../../blocks/news-ticker/lang/en.json";
import newsTicker_it from "../../blocks/news-ticker/lang/it.json";
import paragraph_de from "../../blocks/paragraph/lang/de.json";
import paragraph_en from "../../blocks/paragraph/lang/en.json";
import paragraph_it from "../../blocks/paragraph/lang/it.json";
import quote_de from "../../blocks/quote/lang/de.json";
import quote_en from "../../blocks/quote/lang/en.json";
import quote_it from "../../blocks/quote/lang/it.json";
import socialSharing_de from "../../blocks/social-sharing/lang/de.json";
import socialSharing_en from "../../blocks/social-sharing/lang/en.json";
import socialSharing_it from "../../blocks/social-sharing/lang/it.json";
import starRating_de from "../../blocks/star-rating/lang/de.json";
import starRating_en from "../../blocks/star-rating/lang/en.json";
import starRating_it from "../../blocks/star-rating/lang/it.json";
import syntaxHighlighter_de from "../../blocks/syntax-highlighter/lang/de.json";
import syntaxHighlighter_en from "../../blocks/syntax-highlighter/lang/en.json";
import syntaxHighlighter_it from "../../blocks/syntax-highlighter/lang/it.json";
import table_de from "../../blocks/table/lang/de.json";
import table_en from "../../blocks/table/lang/en.json";
import table_it from "../../blocks/table/lang/it.json";
import testimonials_de from "../../blocks/testimonials/lang/de.json";
import testimonials_en from "../../blocks/testimonials/lang/en.json";
import testimonials_it from "../../blocks/testimonials/lang/it.json";
import video_de from "../../blocks/video/lang/de.json";
import video_en from "../../blocks/video/lang/en.json";
import video_it from "../../blocks/video/lang/it.json";

export const blockMessages: Record<string, Record<string, Record<string, string>>> = {
  audio: {
    de: audio_de,
    en: audio_en,
    it: audio_it,
  },
  button: {
    de: button_de,
    en: button_en,
    it: button_it,
  },
  carousel: {
    de: carousel_de,
    en: carousel_en,
    it: carousel_it,
  },
  chart: {
    de: chart_de,
    en: chart_en,
    it: chart_it,
  },
  code: {
    de: code_de,
    en: code_en,
    it: code_it,
  },
  columns: {
    de: columns_de,
    en: columns_en,
    it: columns_it,
  },
  countdown: {
    de: countdown_de,
    en: countdown_en,
    it: countdown_it,
  },
  counter: {
    de: counter_de,
    en: counter_en,
    it: counter_it,
  },
  delimiter: {
    de: delimiter_de,
    en: delimiter_en,
    it: delimiter_it,
  },
  embed: {
    de: embed_de,
    en: embed_en,
    it: embed_it,
  },
  flickr: {
    de: flickr_de,
    en: flickr_en,
    it: flickr_it,
  },
  gallery: {
    de: gallery_de,
    en: gallery_en,
    it: gallery_it,
  },
  header: {
    de: header_de,
    en: header_en,
    it: header_it,
  },
  html: {
    de: html_de,
    en: html_en,
    it: html_it,
  },
  image: {
    de: image_de,
    en: image_en,
    it: image_it,
  },
  instagram: {
    de: instagram_de,
    en: instagram_en,
    it: instagram_it,
  },
  list: {
    de: list_de,
    en: list_en,
    it: list_it,
  },
  "news-ticker": {
    de: newsTicker_de,
    en: newsTicker_en,
    it: newsTicker_it,
  },
  paragraph: {
    de: paragraph_de,
    en: paragraph_en,
    it: paragraph_it,
  },
  quote: {
    de: quote_de,
    en: quote_en,
    it: quote_it,
  },
  "social-sharing": {
    de: socialSharing_de,
    en: socialSharing_en,
    it: socialSharing_it,
  },
  "star-rating": {
    de: starRating_de,
    en: starRating_en,
    it: starRating_it,
  },
  "syntax-highlighter": {
    de: syntaxHighlighter_de,
    en: syntaxHighlighter_en,
    it: syntaxHighlighter_it,
  },
  table: {
    de: table_de,
    en: table_en,
    it: table_it,
  },
  testimonials: {
    de: testimonials_de,
    en: testimonials_en,
    it: testimonials_it,
  },
  video: {
    de: video_de,
    en: video_en,
    it: video_it,
  },
};
