#!/usr/bin/env node
/**
 * Auto-discovery codegen
 * ───────────────────────
 * Scans blocks/ and plugins/ for subdirectories and regenerates:
 *   .generated/blocks/index.ts           — editor block registry
 *   .generated/blocks/layout-registry.ts — public layout map
 *   .generated/plugins/index.ts          — plugin installer
 *
 * Run manually:  npm run codegen
 * Runs automatically on every `next dev` / `next build` startup.
 *
 * Convention for container blocks:
 *   Export `isContainer` and/or `getChildBlocks` as named exports from
 *   your block's layout.tsx. The codegen script will detect them and wire
 *   them into the public layout registry automatically.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const blocksDir  = join(__dirname, "../blocks");
const pluginsDir = join(__dirname, "../plugins");

// ── Helpers ───────────────────────────────────────────────────────────────────

/** "social-sharing" → "socialSharing" */
function toCamel(name) {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

/** "social-sharing" → "SocialSharing" */
function toPascal(name) {
  const c = toCamel(name);
  return c[0].toUpperCase() + c.slice(1);
}

/** Read layout.tsx and detect exported container helpers. */
function containerExports(name) {
  const layoutPath = join(blocksDir, name, "layout.tsx");
  if (!existsSync(layoutPath)) return { isContainer: false, getChildBlocks: false };
  const src = readFileSync(layoutPath, "utf8");
  return {
    isContainer:    /export\s+(const|let|var)\s+isContainer\b/.test(src),
    getChildBlocks: /export\s+(function|const|let|var)\s+getChildBlocks\b/.test(src),
  };
}

// ── Discover blocks ───────────────────────────────────────────────────────────

const allDirs = readdirSync(blocksDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

const configBlocks = allDirs.filter((n) => existsSync(join(blocksDir, n, "config.tsx")));
const layoutBlocks = allDirs.filter((n) => existsSync(join(blocksDir, n, "layout.tsx")));

// ── Generate blocks/index.ts ──────────────────────────────────────────────────

function genIndex() {
  const imports = configBlocks
    .map((n) => `import ${toCamel(n)} from "../../blocks/${n}/config";`)
    .join("\n");

  const list = configBlocks.map(toCamel).join(", ");

  return `/**
 * Blocks — public entry point
 * ────────────────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a block: create a folder under blocks/ with a config.tsx file.
 * The next dev / build process regenerates this file automatically.
 *
 * Quick reference:
 *
 *   // Define and register a custom block:
 *   import { registerBlock, type BlockDefinition } from "@/blocks";
 *
 *   // Look up a registered block at runtime:
 *   import { blockMap, blockRegistry } from "@/blocks";
 *
 *   // Register a custom icon for use in the block picker:
 *   import { registerIcon } from "@/blocks";
 */

${imports}

import {
  registerBlock,
  unregisterBlock,
  blockRegistry,
  blockMap,
  registerIcon,
  getPluginIcon,
} from "@/lib/plugin-registry";

for (const block of [${list}]) {
  registerBlock(block);
}

// ── Block registry ────────────────────────────────────────────────────────────
export { blockRegistry, blockMap };

// ── Registration API ──────────────────────────────────────────────────────────
export { registerBlock, unregisterBlock, registerIcon, getPluginIcon };

// ── Types ─────────────────────────────────────────────────────────────────────
export type {
  BlockDefinition,
  BlockData,
  BlockLayoutProps,
  EditableProps,
  PanelControlProps,
} from "@/lib/block-types";
`;
}

// ── Generate blocks/layout-registry.ts ───────────────────────────────────────

function genLayoutRegistry() {
  const importLines = layoutBlocks.map((name) => {
    const pascal = toPascal(name);
    const camel  = toCamel(name);
    const cx = containerExports(name);
    const named = [
      cx.isContainer    && `isContainer as ${camel}IsContainer`,
      cx.getChildBlocks && `getChildBlocks as ${camel}GetChildBlocks`,
    ].filter(Boolean);

    return named.length
      ? `import ${pascal}Layout, { ${named.join(", ")} } from "../../blocks/${name}/layout";`
      : `import ${pascal}Layout from "../../blocks/${name}/layout";`;
  });

  const mapEntries = layoutBlocks.map((name) => {
    const pascal = toPascal(name);
    const camel  = toCamel(name);
    const key    = name.includes("-") ? `"${name}"` : name;
    const cx     = containerExports(name);

    if (cx.isContainer || cx.getChildBlocks) {
      const extras = [
        cx.isContainer    && `    isContainer: ${camel}IsContainer,`,
        cx.getChildBlocks && `    getChildBlocks: ${camel}GetChildBlocks,`,
      ].filter(Boolean).join("\n");
      return `  ${key}: {\n    Layout: ${pascal}Layout,\n${extras}\n  },`;
    }
    return `  ${key}: { Layout: ${pascal}Layout },`;
  });

  return `/**
 * Public block layout registry
 * ──────────────────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a block: create a folder under blocks/ with a layout.tsx file.
 * The next dev / build process regenerates this file automatically.
 *
 * Container blocks: export \`isContainer\` and/or \`getChildBlocks\` from
 * your layout.tsx and they will be picked up automatically.
 *
 * This module intentionally does NOT import Editable or PanelControls
 * components, keeping them out of the public page bundle. The full registry
 * (including all editor components) lives in blocks/index.ts and is used
 * only by the admin editor.
 *
 * Plugin authors can call registerPublicLayout() to make their custom blocks
 * renderable on public pages without pulling in editor-only code.
 */

import type { ReactNode } from "react";
import type { EditorBlock } from "@/lib/types";
import type { BlockLayoutProps } from "@/lib/block-types";

${importLines.join("\n")}

export interface PublicBlockDef {
  Layout: (props: BlockLayoutProps) => ReactNode;
  isContainer?: boolean;
  getChildBlocks?: (data: Record<string, unknown>) => EditorBlock[][];
}

export const publicBlockMap: Record<string, PublicBlockDef> = {
${mapEntries.join("\n")}
};

/**
 * Register a custom block's Layout in the public renderer.
 * Call this in plugin code to make plugin-defined blocks visible on public
 * pages without importing editor-only Editable / PanelControls components.
 */
export function registerPublicLayout(name: string, def: PublicBlockDef): void {
  publicBlockMap[name] = def;
}
`;
}

// ── Discover plugins ──────────────────────────────────────────────────────────

const pluginDirs = readdirSync(pluginsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(pluginsDir, d.name, "index.ts")))
  .map((d) => d.name)
  .sort();

// ── Generate .generated/plugins/index.ts ─────────────────────────────────────

function genPlugins() {
  const imports = pluginDirs
    .map((n) => `import ${toCamel(n)} from "../../plugins/${n}";`)
    .join("\n");

  const installs = pluginDirs
    .map((n) => `installPlugin(${toCamel(n)});`)
    .join("\n");

  return `/**
 * Plugin installer
 * ─────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a plugin: create a folder under plugins/ with an index.ts that
 * exports a PluginDefinition as its default export.
 * The next dev / build process regenerates this file automatically.
 */

import fs from "fs";
import path from "path";
import { installPlugin, setDisabledChecker } from "@/lib/plugin-registry";
${imports}

// Install a file-backed disabled checker.  The guarded filter wrapper calls
// this on every filter invocation so it always reflects the current
// plugin-states.json regardless of which module context (RSC vs Route Handler)
// is running — those contexts have separate in-memory module instances and
// cannot share a Set reliably.
const _STATES_FILE = path.join(process.cwd(), "data", "plugin-settings", "plugin-states.json");
let _statesCache: Record<string, boolean> = {};
let _statesCacheTs = 0;

setDisabledChecker((name: string): boolean => {
  const now = Date.now();
  if (now - _statesCacheTs > 500) {
    try {
      _statesCache = JSON.parse(fs.readFileSync(_STATES_FILE, "utf-8")) as Record<string, boolean>;
    } catch {
      // No states file yet — disable the example plugin by default so a fresh
      // install does not pop an alert on every visitor's browser.
      _statesCache = { "alert-on-load": false };
    }
    _statesCacheTs = now;
  }
  // absent = enabled, explicit false = disabled
  return _statesCache[name] === false;
});

${installs}
`;
}

// ── Write files ───────────────────────────────────────────────────────────────

const generatedDir = join(__dirname, "../.generated");
mkdirSync(join(generatedDir, "blocks"),   { recursive: true });
mkdirSync(join(generatedDir, "plugins"),  { recursive: true });

writeFileSync(join(generatedDir, "blocks",  "index.ts"),          genIndex(),          "utf8");
writeFileSync(join(generatedDir, "blocks",  "layout-registry.ts"), genLayoutRegistry(), "utf8");
writeFileSync(join(generatedDir, "plugins", "index.ts"),           genPlugins(),        "utf8");

console.log(
  `✓ codegen: ${configBlocks.length} blocks, ${pluginDirs.length} plugins`
);
