/**
 * Plugin installer
 * ─────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a plugin: create a folder under plugins/ with an index.ts that
 * exports a PluginDefinition as its default export.
 * The next dev / build process regenerates this file automatically.
 */

import fs from "fs";
import path from "path";
import { installPlugin, setDisabledChecker } from "@/lib/plugin-registry";
import alertOnLoad from "../../plugins/alert-on-load";

// Install a file-backed disabled checker.  The guarded filter wrapper calls
// this on every filter invocation so it always reflects the current
// plugin-states.json regardless of which module context (RSC vs Route Handler)
// is running — those contexts have separate in-memory module instances and
// cannot share a Set reliably.
const _STATES_FILE = path.join(process.cwd(), "data", "plugin-settings", "plugin-states.json");
let _statesCache: Record<string, boolean> = {};
let _statesCacheTs = 0;

setDisabledChecker((name: string): boolean => {
  const now = Date.now();
  if (now - _statesCacheTs > 500) {
    try {
      _statesCache = JSON.parse(fs.readFileSync(_STATES_FILE, "utf-8")) as Record<string, boolean>;
    } catch {
      // No states file yet — disable the example plugin by default so a fresh
      // install does not pop an alert on every visitor's browser.
      _statesCache = { "alert-on-load": false };
    }
    _statesCacheTs = now;
  }
  // absent = enabled, explicit false = disabled
  return _statesCache[name] === false;
});

installPlugin(alertOnLoad);
