/**
 * Blocks — public entry point
 * ────────────────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a block: create a folder under blocks/ with a config.tsx file.
 * The next dev / build process regenerates this file automatically.
 *
 * Quick reference:
 *
 *   // Define and register a custom block:
 *   import { registerBlock, type BlockDefinition } from "@/blocks";
 *
 *   // Look up a registered block at runtime:
 *   import { blockMap, blockRegistry } from "@/blocks";
 *
 *   // Register a custom icon for use in the block picker:
 *   import { registerIcon } from "@/blocks";
 */

import audio from "../../blocks/audio/config";
import button from "../../blocks/button/config";
import carousel from "../../blocks/carousel/config";
import chart from "../../blocks/chart/config";
import code from "../../blocks/code/config";
import columns from "../../blocks/columns/config";
import countdown from "../../blocks/countdown/config";
import counter from "../../blocks/counter/config";
import delimiter from "../../blocks/delimiter/config";
import embed from "../../blocks/embed/config";
import flickr from "../../blocks/flickr/config";
import gallery from "../../blocks/gallery/config";
import header from "../../blocks/header/config";
import html from "../../blocks/html/config";
import image from "../../blocks/image/config";
import instagram from "../../blocks/instagram/config";
import list from "../../blocks/list/config";
import newsTicker from "../../blocks/news-ticker/config";
import paragraph from "../../blocks/paragraph/config";
import quote from "../../blocks/quote/config";
import socialSharing from "../../blocks/social-sharing/config";
import starRating from "../../blocks/star-rating/config";
import syntaxHighlighter from "../../blocks/syntax-highlighter/config";
import table from "../../blocks/table/config";
import testimonials from "../../blocks/testimonials/config";
import video from "../../blocks/video/config";

import {
  registerBlock,
  unregisterBlock,
  blockRegistry,
  blockMap,
  registerIcon,
  getPluginIcon,
} from "@/lib/plugin-registry";

for (const block of [audio, button, carousel, chart, code, columns, countdown, counter, delimiter, embed, flickr, gallery, header, html, image, instagram, list, newsTicker, paragraph, quote, socialSharing, starRating, syntaxHighlighter, table, testimonials, video]) {
  registerBlock(block);
}

// ── Block registry ────────────────────────────────────────────────────────────
export { blockRegistry, blockMap };

// ── Registration API ──────────────────────────────────────────────────────────
export { registerBlock, unregisterBlock, registerIcon, getPluginIcon };

// ── Types ─────────────────────────────────────────────────────────────────────
export type {
  BlockDefinition,
  BlockData,
  BlockLayoutProps,
  EditableProps,
  PanelControlProps,
} from "@/lib/block-types";
