/**
 * Public block layout registry
 * ──────────────────────────────
 * AUTO-GENERATED by lib/codegen.mjs — do not edit manually.
 * To add a block: create a folder under blocks/ with a layout.tsx file.
 * The next dev / build process regenerates this file automatically.
 *
 * Container blocks: export `isContainer` and/or `getChildBlocks` from
 * your layout.tsx and they will be picked up automatically.
 *
 * This module intentionally does NOT import Editable or PanelControls
 * components, keeping them out of the public page bundle. The full registry
 * (including all editor components) lives in blocks/index.ts and is used
 * only by the admin editor.
 *
 * Plugin authors can call registerPublicLayout() to make their custom blocks
 * renderable on public pages without pulling in editor-only code.
 */

import type { ReactNode } from "react";
import type { EditorBlock } from "@/lib/types";
import type { BlockLayoutProps } from "@/lib/block-types";

import AudioLayout from "../../blocks/audio/layout";
import ButtonLayout from "../../blocks/button/layout";
import CarouselLayout from "../../blocks/carousel/layout";
import ChartLayout from "../../blocks/chart/layout";
import CodeLayout from "../../blocks/code/layout";
import ColumnsLayout, { isContainer as columnsIsContainer, getChildBlocks as columnsGetChildBlocks } from "../../blocks/columns/layout";
import CountdownLayout from "../../blocks/countdown/layout";
import CounterLayout from "../../blocks/counter/layout";
import DelimiterLayout from "../../blocks/delimiter/layout";
import EmbedLayout from "../../blocks/embed/layout";
import FlickrLayout from "../../blocks/flickr/layout";
import GalleryLayout from "../../blocks/gallery/layout";
import HeaderLayout from "../../blocks/header/layout";
import HtmlLayout from "../../blocks/html/layout";
import ImageLayout from "../../blocks/image/layout";
import InstagramLayout from "../../blocks/instagram/layout";
import ListLayout from "../../blocks/list/layout";
import NewsTickerLayout from "../../blocks/news-ticker/layout";
import ParagraphLayout from "../../blocks/paragraph/layout";
import QuoteLayout from "../../blocks/quote/layout";
import SocialSharingLayout from "../../blocks/social-sharing/layout";
import StarRatingLayout from "../../blocks/star-rating/layout";
import SyntaxHighlighterLayout from "../../blocks/syntax-highlighter/layout";
import TableLayout from "../../blocks/table/layout";
import TestimonialsLayout from "../../blocks/testimonials/layout";
import VideoLayout from "../../blocks/video/layout";

export interface PublicBlockDef {
  Layout: (props: BlockLayoutProps) => ReactNode;
  isContainer?: boolean;
  getChildBlocks?: (data: Record<string, unknown>) => EditorBlock[][];
}

export const publicBlockMap: Record<string, PublicBlockDef> = {
  audio: { Layout: AudioLayout },
  button: { Layout: ButtonLayout },
  carousel: { Layout: CarouselLayout },
  chart: { Layout: ChartLayout },
  code: { Layout: CodeLayout },
  columns: {
    Layout: ColumnsLayout,
    isContainer: columnsIsContainer,
    getChildBlocks: columnsGetChildBlocks,
  },
  countdown: { Layout: CountdownLayout },
  counter: { Layout: CounterLayout },
  delimiter: { Layout: DelimiterLayout },
  embed: { Layout: EmbedLayout },
  flickr: { Layout: FlickrLayout },
  gallery: { Layout: GalleryLayout },
  header: { Layout: HeaderLayout },
  html: { Layout: HtmlLayout },
  image: { Layout: ImageLayout },
  instagram: { Layout: InstagramLayout },
  list: { Layout: ListLayout },
  "news-ticker": { Layout: NewsTickerLayout },
  paragraph: { Layout: ParagraphLayout },
  quote: { Layout: QuoteLayout },
  "social-sharing": { Layout: SocialSharingLayout },
  "star-rating": { Layout: StarRatingLayout },
  "syntax-highlighter": { Layout: SyntaxHighlighterLayout },
  table: { Layout: TableLayout },
  testimonials: { Layout: TestimonialsLayout },
  video: { Layout: VideoLayout },
};

/**
 * Register a custom block's Layout in the public renderer.
 * Call this in plugin code to make plugin-defined blocks visible on public
 * pages without importing editor-only Editable / PanelControls components.
 */
export function registerPublicLayout(name: string, def: PublicBlockDef): void {
  publicBlockMap[name] = def;
}
